export const industries = {
    101: 'Accounting & Finance',
    102: 'Advertising & Marketing',
    103: 'Agriculture, Forestry & Fishing',
    104: 'Airlines & Aviation',
    105: 'Arts, Fashion & Design',
    106: 'Automotive & Vehicle Repair',
    107: 'Banking & Financial Services',
    108: 'Construction & Building Service',
    109: 'Consulting & Project Management',
    110: 'Customer Service & Call Centre',
    111: 'Education & Training',
    112: 'Engineering & Architecture',
    113: 'Environment, Health & Safety',
    114: 'Government & Public Sector',
    115: 'Healthcare & Medical',
    116: 'Hospitality, Tourism & Food Service',
    117: 'Human Resources & Recruitment',
    118: 'Humanitarian ',
    119: 'Information & Communication Technology',
    120: 'Installation, Maintenance & Repair',
    121: 'Insurance',
    122: 'Land Use & Environmental Management',
    123: 'Legal',
    124: 'Library & Records Management',
    125: 'Management',
    126: 'Manufacturing',
    127: 'Marine',
    128: 'Media & Corporate Communications',
    129: 'Mining, Resources & Energy ',
    130: 'Procurement, Logistics & Supply Chain',
    131: 'Quality Assurance',
    132: 'Railway & Railtrack',
    133: 'Real Estate',
    134: 'Religion',
    135: 'Research, Monitoring & Evaluation',
    136: 'Retail',
    137: 'Sales and Business Development',
    138: 'Scientific',
    139: 'Secretarial Administrative & Clerical',
    140: 'Security & Armed Forces',
    141: 'Sports & Leisure',
    142: 'Utilities'
};

export const canadaProvinces = {
    300: 'Alberta',
    301: 'British Columbia',
    302: 'Manitoba',
    303: 'New Brunswick',
    304: 'Newfoundland and Labrador',
    305: 'Nova Scotia',
    306: 'Ontario',
    307: 'Prince Edward Island',
    308: 'Quebec',
    309: 'Saskatchewan'
};

export const COUNTRIES = ['Afghanistan', 'Algeria', 'Angola', 'Antarctica', 'Armenia', 'Azerbaijan', 'Bangladesh', 'Belize', 'Benin', 'Bhutan', 'Botswana', 'Bouvet Island', 'British Indian Ocean Territory', 'Brunei Darussalam', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'China', 'Comoros', 'Congo', 'Congo (the Democratic Republic of the)', "Côte d'Ivoire", 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Heard Island and McDonald Islands', 'Hong Kong', 'India', 'Indonesia', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Lesotho', 'Liberia', 'Libya', 'Macao', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Mauritania', 'Mauritius', 'Mayotte', 'Mongolia', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Niger', 'Nigeria', 'North Korea', 'Pakistan', 'Philippines', 'Rwanda', 'Réunion', 'Saint Helena, Ascension and Tristan da Cunha', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'South Korea', 'South Sudan', 'Sri Lanka', 'Sudan', 'Taiwan (Province of China)', 'Tajikistan', 'Tanzania, the United Republic of', 'Thailand', 'Timor-Leste', 'Togo', 'Tunisia', 'Turkmenistan', 'Uganda', 'Uzbekistan', 'Viet Nam', 'Western Sahara', 'Zambia', 'Zimbabwe'];

export const statusInCountryOfResidence = ['citizen', 'resident', 'worker', 'student', 'visitor', 'no status']